name: Code quality check
description: Installs dependencies and checks TS & linting
runs:
  using: 'composite'
  steps:
    - run: yarn install
      shell: bash

    - name: Check TypeScript
      run: yarn ts
      shell: bash

    - name: Check ESLint
      run: yarn lint
      shell: bash
