name: Code quality check

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies and code quality check
        uses: ./.github/workflows/code-quality-check
